"""auto-vote

Revision ID: 536cd96ffb90
Revises: 912dcc052488
Create Date: 2022-03-23 15:06:42.064270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536cd96ffb90'
down_revision = '912dcc052488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.add_column('posts', sa.Column('rating', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'rating')
    op.drop_table('votes')
    # ### end Alembic commands ###
